=== lsmoura/poejson/gems.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://poejson.com/gems.schema.json",
  "title": "Gems",
  "description": "Current valid game gems",
  "type": "object",
  "properties": {
    "name": {
      "description": "the name of the gem",
      "type": "string"
    },
    "colour": {
      "description": "the colour of the gem",
      "enum": ["R", "G", "B", "W"]
    },
    "description": {
      "description": "the description of the gem",
      "type": "string"
    },
    "tags": {
      "description": "the gem's tags",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "cost": {
      "description": "cost range of the gem from minimum to maximum gem level (note that the gem level can be expanded above its maximum level). support gems do not have this property.",
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        }
      },
      "required": ["min", "max"]
    },
    "transfigured": {
      "type": "boolean"
    },
    "awakened": {
      "type": "boolean"
    },
    "required_level": {
      "description": "minimum character level to use the gem at level 1",
      "type": "number"
    },
    "store_count": {
      "type": "number"
    },
    "cast_time": {
      "description": "seconds to cast the skill",
      "type": "number"
    },
    "critical_chance": {
      "description": "probability to deal critical damage",
      "type": "number"
    },
    "cooldown": {
      "type": "number"
    },    
    "added_damage_effectiveness": {
      "type": "number"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true      
    },
    "quality_effects": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true      
    },
    "max_level": {
      "description": "Maximum level of this gem. If omitted, the maximum level is assumed to be the default: 20",
      "type": "number"
    },
    "reservation": {
      "description": "aura skills don't have a cost. they have reservation instead.",
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "perc": {
          "description": "if true, the informed value is a percentage of the resource",
          "type": "boolean"
        }
      },
      "required": ["min", "max"]
    },
    "souls": {
      "description": "number of souls needed to earn one charge of the spell",
      "type": "number"
    },
    "soul_gain_prevention": {
      "description": "number of seconds that the player won't be able to earn souls for this spell after it's cast",
      "type": "number"
    }
  },
  "required": [
    "name",
    "colour",
    "description"
  ]
}

=== lsmoura/poejson/gems/summon-stone-golem.json
{
  "name": "Summon Stone Golem",
  "colour": "R",
  "required_level": 34,
  "tags": ["minion", "spell", "golem", "physical"],
  "description": "Summons a Stone Golem that grants you life regeneration. In addition to its melee attack, the Stone Golem uses a rolling charge and a powerful slam that can taunt enemies.",
  "cost": { "min": 30, "max": 54 },
  "cooldown": 6,
  "cast_time": 1,
  "effects": [
    "Maximum 1 Summoned Golem",
    "Golems grant (33-105) Life Regenerated per second"
  ],
  "quality_effects": [
    "1% increased Buff Effect"
  ]
}

=== lsmoura/poejson/gems/vaal-breach.json
{
  "name": "Vaal Breach",
  "colour": "W",
  "required_level": 10,
  "souls": 100,
  "soul_gain_prevention": 40,
  "max_level": 1,
  "tags": ["spell", "vaal"],
  "description": "Creates a breach, making you vulnerable to its powerful inhabitants.",
  "cast_time": 2.5,
  "effects": [
    "Monsters from the Breach do not grant Experience or drop Items"
  ],
  "quality_effects": [
    "3% increased Cast Speed"
  ]
}

=== lsmoura/poejson/gems/absolution-of-inspiring.json
{
  "name": "Absolution of Inspiring",
  "transfigured": true,
  "colour": "R",
  "required_level": 12,
  "tags": ["spell", "minion", "duration", "physical", "lightning", "aoe"],
  "description": "Damages enemies in an area, applying a debuff for a short duration. If a non-unique enemy dies while affected by the debuff, the corpse will be consumed to summon a Sentinel of Absolution for a secondary duration, or to refresh the duration and life of an existing one instead if you have the maximum number of them.",
  "cost": { "min": 9, "max": 26 },
  "cast_time": 0.75,
  "critical_chance": 0.06,
  "added_damage_effectiveness": 2,
  "effects": [
    "Deals (21-873) to (31-1310) Physical Damage",
    "Base duration is 1.00 seconds",
    "Base secondary duration is 10.00 seconds",
    "Increases and Reductions to Minion Damage also apply to this Skill's Damage at 200% of their value",
    "+(0-0.6) metres to radius",
    "25% chance to Summon a Sentinel of Absolution on Hitting a Rare or Unique Enemy",
    "This Spell and Minions Convert 50% of Physical Damage to Lightning Damage",
    "Maximum 2 Summoned Sentinels of Absolution"
  ],
  "quality_effects": [
    "Increases and Reductions to Minion Damage also apply to this Skill's Damage at 2.5% of their value"
  ]
}

=== lsmoura/poejson/gems/summon-stone-golem-of-hordes.json
{
  "name": "Summon Stone Golem of Hordes",
  "transfigured": true,
  "colour": "R",
  "required_level": 34,
  "tags": ["minion", "spell", "golem", "physical"],
  "description": "Summons a Stone Golem. In addition to its melee attack, the Stone Golem uses a rolling charge and a powerful slam that can taunt enemies.",
  "cost": { "min": 30, "max": 54 },
  "cooldown": 6,
  "cast_time": 1,
  "effects": [
    "Maximum 3 Summoned Golems"
  ],
  "quality_effects": [
    "Minions have 2% increased Cooldown Recovery Rate"
  ]
}

=== lsmoura/poejson/gems/storm-brand-of-indecision.json
{
  "name": "Storm Brand of Indecision",
  "transfigured": true,
  "colour": "B",
  "required_level": 12,
  "tags": ["lightning", "spell", "aoe", "chaining", "duration", "brand"],
  "description": "Creates a magical brand which can attach to a nearby enemy. It periodically activates while attached, firing beams which deal damage to nearby enemies and those around them. The brand will detach if the enemy dies.",
  "cost": { "min": 8, "max": 21 },
  "cast_time": 0.35,
  "critical_chance": 0.06,
  "added_damage_effectiveness": 0.85,
  "effects": [
    "Deals (6-229) to (19-686) Lightning Damage",
    "Activates every 0.4 seconds while Attached",
    "Increases and Reductions to Cast Speed also apply to this Skill's Activation frequency",
    "Attaches to a new Enemy after Activating, no more than once every 0.3 seconds",
    "Can be Detached for a total Duration of 6.00 seconds",
    "Can be Attached for a total Duration of 5.00 seconds",
    "Sends a beam to the Branded Enemy"
  ],
  "quality_effects": [
    "Deals +1% more Damage with Hits against Branded Enemy"
  ]
}

=== lsmoura/poejson/gems/detonate-mines.json
{
  "name": "Detonate Mines",
  "colour": "W",
  "required_level": 8,
  "max_level": 1,
  "tags": ["mine", "spell"],
  "description": "Detonates a Mine, starting a Detonation Sequence which will detonate other Mines around it.",
  "cast_time": 0,
  "cooldown": 0.2,
  "effects": [
    "First Mine Detonates Instantly",
    "Mines get 10% more Detonation Speed for each prior Mine in Detonation Sequence"
  ],
  "quality_effects": [
    "Mines have 1% increased Detonation Speed"
  ]
}

=== lsmoura/poejson/gems/storm-brand.json
{
  "name": "Storm Brand",
  "colour": "B",
  "required_level": 12,
  "tags": ["lightning", "spell", "aoe", "chaining", "duration", "brand"],
  "description": "Creates a magical brand which can attach to a nearby enemy. It periodically activates while attached, firing beams which deal damage to nearby enemies and those around them. The brand will detach if the enemy dies.",
  "cost": { "min": 8, "max": 21 },
  "cast_time": 0.75,
  "critical_chance": 0.06,
  "added_damage_effectiveness": 0.3,
  "effects": [
    "Deals (3-92) to (8-277) Lightning Damage",
    "Activates every 0.5 seconds while Attached",
    "Increases and Reductions to Cast Speed also apply to this Skill's Activation frequency",
    "Can be Detached for a total Duration of 6.00 seconds",
    "Can be Attached for a total Duration of 5.00 seconds",
    "Sends beams to 3 Enemies, including the Branded Enemy",
    "Deals (80-130)% more Damage with Hits against Branded Enemy"
  ],
  "quality_effects": [
    "Sends beams to +0.05 Enemies"
  ]
}

=== lsmoura/poejson/gems/precision.json
{
  "name": "Precision",
  "colour": "G",
  "required_level": 10,
  "tags": ["aura", "critical", "spell", "aoe"],
  "description": "Casts an aura that grants accuracy and critical strike chance to you and your allies.",
  "reservation": { "min": 22, "max": 186 },
  "cast_time": 0,
  "cooldown": 1.2,
  "effects": [
    "+(0-1.9) metres to radius",
    "You and nearby allies gain (20-58)% increased Critical Strike Chance",
    "You and nearby allies gain +(93-701) to Accuracy Rating"
  ],
  "quality_effects": [
    "2% increased Area of Effect"
  ]
}
