=== lsmoura/poejson/gems.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://poejson.com/gems.schema.json",
  "title": "Gems",
  "description": "Current valid game gems",
  "type": "object",
  "properties": {
    "name": {
      "description": "the name of the gem",
      "type": "string"
    },
    "colour": {
      "description": "the colour of the gem",
      "enum": ["R", "G", "B", "W"]
    },
    "description": {
      "description": "the description of the gem",
      "type": "string"
    },
    "tags": {
      "description": "the gem's tags",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "cost": {
      "description": "cost range of the gem from minimum to maximum gem level (note that the gem level can be expanded above its maximum level). support gems do not have this property.",
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        }
      },
      "required": ["min", "max"]
    },
    "transfigured": {
      "type": "boolean"
    },
    "awakened": {
      "type": "boolean"
    },
    "required_level": {
      "description": "minimum character level to use the gem at level 1",
      "type": "number"
    },
    "store_count": {
      "type": "number"
    },
    "cast_time": {
      "description": "seconds to cast the skill",
      "type": "number"
    },
    "critical_chance": {
      "description": "probability to deal critical damage",
      "type": "number"
    },
    "cooldown": {
      "type": "number"
    },    
    "added_damage_effectiveness": {
      "type": "number"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true      
    },
    "quality_effects": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true      
    },
    "max_level": {
      "description": "Maximum level of this gem. If omitted, the maximum level is assumed to be the default: 20",
      "type": "number"
    },
    "reservation": {
      "description": "aura skills don't have a cost. they have reservation instead.",
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "perc": {
          "description": "if true, the informed value is a percentage of the resource",
          "type": "boolean"
        }
      },
      "required": ["min", "max"]
    },
    "souls": {
      "description": "number of souls needed to earn one charge of the spell",
      "type": "number"
    },
    "soul_gain_prevention": {
      "description": "number of seconds that the player won't be able to earn souls for this spell after it's cast",
      "type": "number"
    }
  },
  "required": [
    "name",
    "colour",
    "description"
  ]
}

=== lsmoura/poejson/gems/summon-stone-golem-of-safeguarding.json
{
  "name": "Summon Stone Golem of Safeguarding",
  "transfigured": true,
  "colour": "R",
  "required_level": 34,
  "tags": ["minion", "spell", "golem", "physical"],
  "description": "Summons a Stone Golem that takes a portion of the melee damage you recieve from enemy hits from its life before yours. In addition to its melee attack, the Stone Golem uses a rolling charge and a powerful slam that can taunt enemies.",
  "cost": { "min": 30, "max": 54 },
  "cooldown": 15,
  "cast_time": 1,
  "effects": [
    "Maximum 1 Summoned Golem",
    "Minions have 50% less Maximum Life",
    "Golems grant 10% of Melee Damage is taken from your Stone Golems' Life before you"
  ],
  "quality_effects": [
    "1% increased Buff Effect"
  ]
}

=== lsmoura/poejson/gems/flame-dash.json
{
  "name": "Flame Dash",
  "colour": "R",
  "required_level": 10,
  "tags": ["spell", "movement", "duration", "fire", "travel", "blink"],
  "description": "Teleport to a location, damaging enemies and leaving a trail of burning ground. Shares a cooldown with other Blink skills.",
  "cost": { "min": 8, "max": 23 },
  "cast_time": 0.8,
  "cooldown": 3.5,
  "store_count": 3,
  "critical_chance": 0.06,
  "added_damage_effectiveness": 1.4,
  "effects": [
    "Deals (19.7-1738.6) Base Fire Damage per second",
    "Base duration is 4.00 seconds",
    "Deals (7-659) to (11-988) Fire Damage",
    "Modifiers to Spell Damage apply to this Skill's Damage Over Time effect",
    "(0-19)% increased Cooldown Recovery Rate"
  ],
  "quality_effects": [
    "0.5% increased Cooldown Recovery Rate"
  ]
}
